### ISSUE TITLE
gravity in porous media

### ISSUE THREAD

**Issue by longhuang123** [Franjcf/hybridPorousInterFoam#4]
Hello, I found that the gravity setting is only effective when eps is 0.999, but not in porous media. I would like to know how to consider gravity in porous media, thank you

**Comment by Franjcf** [comment]
Hi. 

Gravity is considered both in the porous medium and in the free fluid. Please refer to the JCP paper at the end of the README file for a complete derivation of the equations. In short, the "rho"-dependent gravity term in pEqn.H is defined differently depending on the domain that each grid cell is on, this is controlled by the "Solid" variable (equal to 1 in porous media and 0 in solid-free domains). rho itself is defined at the end of the alphaEqnSubCycle.H file and is in agreement with Eqn. 39 shown in the paper.

**Comment by longhuang123** [comment]
Hi.
I want to run some examples of coupling free flow and porous media flow. In fact, the fluids in porous media will produce gravitational differentiation due to density difference, but I can't simulate this phenomenon. I changed a lot of parameters, but it has no effect.

**Comment by longhuang123** [comment]
Gravity differentiation only occur when eps is 0.999

**Comment by Franjcf** [comment]
Hi. I suggest you look at the tutorial case within Darcy_Flow_Cases/Gravity_Capillarity_Equilibrium and the associated explanation the paper I referenced. In this particular tutorial you can clearly see that the density difference between the fluids creates fluid separation in the column (which is then balanced by capillary forces). If I were you, I would play around with this case just to get a feel of how this would work and then apply/modify it to your own system. 

The reason why the solver "works" at eps =0.999 is because the solver switches to the solid-free gravity formulation at this point (i.e. Volume-of-Fluid formulation, not the Darcy formulation). I would also check your particular case just to make sure you are not trying to simulate something that is not physical.

**Comment by longhuang123** [comment]
Thanks for your reply. I will try to design other examples according to your suggestions.
